sudo: required

dist: trusty

language: python

notifications:
  email:
    recipients:
      - martinls@met.no
      - havard.heitlo.holm@sintef.no 

    # Change values when CI is working properly again!
    on_success: never #change
    on_failure: never #always

python:
  - "3.5"

# CUDA will not run on Travis CI. Only "non-GPU" tests will run!
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq lcov curl
    ocl-icd-libopencl1 opencl-headers libnetcdf-dev
    libhwloc-dev libltdl-dev pkg-config libedit-dev
    google-perftools

install:
  - cd python
  - pip install -r requirements.txt
  - cd ..

script:
  - export LD_PRELOAD="/usr/lib/libtcmalloc.so.4"
  - export OCL_ICD_VENDORS=/usr/local/etc/OpenCL/vendors/pocl.icd
  - export COVERALLS_SERVICE_NAME=travis-ci
  - export COVERALLS_REPO_TOKEN=N5DQzXpRwmJg84M0xfeFlDV2D6Zz4yUVt
  - cd python/tests
  - python -m unittest discover . "*_test.py"
# Coveralls is not set up for Python!
#  - python -m pytest -v --cov .. --cov-report term-missing
#  - coveralls

