sudo: required

dist: trusty

language: python

python:
  - "2.7"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq lcov curl libboost-filesystem-dev
    libboost-system-dev libboost-thread-dev libboost-program-options-dev
    libboost-test-dev ocl-icd-libopencl1 opencl-headers libnetcdf-dev
    libhwloc-dev libltdl-dev pkg-config libedit-dev
  - wget https://github.com/pocl/pocl/archive/v1.1.tar.gz
  - tar xzf v1.1.tar.gz && cd pocl-1.1
  - cmake -DENABLE_ICD=OFF .
  - sudo make -j2 && sudo make install
  - cd ..

install:
  - cd python
  - pip install -r requirements.txt
  - cd ..

script:
  - cd python/tests
  - python basic_pyopencl_tests.py
  - python oneLayer_2D_tests.py 0
  - python particle_filter_tests.py 0
  - cd ../..
#  - mkdir build
#  - cd build
#  - export COVERALLS_SERVICE_NAME=travis-ci
#  - export COVERALLS_REPO_TOKEN=N5DQzXpRwmJg84M0xfeFlDV2D6Zz4yUVt
#  - cmake -DCOVERALLS=ON -DCMAKE_BUILD_TYPE=Debug ..
#  - make
#  - export KERNELDIR=../../sim/src/kernels/
#  - make coveralls
